FROM rust:1.84 as build

RUN apt-get update && apt-get install -y --no-install-recommends \
    apt-utils \
    software-properties-common \
    cmake \
    libclang-dev \
    libudev-dev

RUN USER=root cargo new --bin solana
WORKDIR /solana

COPY . /solana

RUN cargo build --release



FROM debian:buster-slim

RUN mkdir -p /solana

WORKDIR /solana

COPY --from=build /solana/target/release/block-meta-rpc .

EXPOSE 8899

CMD ["./block-meta-rpc", "--bind-address=0.0.0.0", "--enable-rpc-mysql-meta-storage", "--rpc-mysql-address=mysql:3306"]